### PR TITLE
Support SwiftPM

### PR DESCRIPTION
**Pull request by toshi0383**
## Overview

- Added Swift Package Manager support
- Added Example target so that user can try it out from CLI
- Supported watchOS and tvOS (as a side effect😉)
- xcodeproj is generated using https://github.com/jakeheis/Ice (`ice xc` command) and manually fixed some references after that.

## important review points

`DEPLOYMENT_TARGET` is not changed.

```
LoremSwiftum $ grep DEPLOYMENT_TARGET LoremSwiftum.xcodeproj/project.pbxproj | sort -u
            IPHONEOS_DEPLOYMENT_TARGET = "8.0";
            MACOSX_DEPLOYMENT_TARGET = "10.10";
            TVOS_DEPLOYMENT_TARGET = "9.0";
            WATCHOS_DEPLOYMENT_TARGET = "2.0";
```

Carthage build is not broken.
```
LoremSwiftum $ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/f1/drl_8qdj0qs19y07br7q313xr5q2d9/T/carthage-xcodebuild.4hztZn.log
*** Building scheme "LoremSwiftum" in LoremSwiftum.xcodeproj
LoremSwiftum $ fd framework
Carthage/Build/Mac/LoremSwiftum.framework
Carthage/Build/Mac/LoremSwiftum.framework.dSYM
Carthage/Build/iOS/LoremSwiftum.framework
Carthage/Build/iOS/LoremSwiftum.framework.dSYM
Carthage/Build/tvOS/LoremSwiftum.framework
Carthage/Build/tvOS/LoremSwiftum.framework.dSYM
Carthage/Build/watchOS/LoremSwiftum.framework
Carthage/Build/watchOS/LoremSwiftum.framework.dSYM
```

Playground still works.
スクリーンショット 2019-10-31 21 48 56

### CODE REVIEW

**Comment by SuperWomble** [comment]
Please accept this request. SPM support would be very useful. Thank you.

**Comment by toshi0383** [comment]
@lukaskubanek If you intend to accept this, I can rebase this.🙆‍♂️ Thank you!

**Comment by lukaskubanek** [comment]
Hi folks, I’ll look into this within the next two weeks.

**Comment by kenji21** [comment]
Conflict might be due to your fork not up to date @toshi0383 :

 "This branch is 6 commits ahead, 4 commits behind lukaskubanek:master."

I think you should update your PR to help review

**Comment by toshi0383** [comment]
@kenji21 Oh I know mate. I've been busy.

**Comment by toshi0383** [comment]
Sorry guys, but I don't have time or motivation to update this PR anymore. Closing this.
Sorry about that, but good luck with you all.👍
Any question is welcome though. If you have anything on my code, please don't hesitate to ask!😉

**Comment by kenji21** [comment]
no problem @toshi0383, just done a simpler one : https://github.com/lukaskubanek/LoremSwiftum/pull/23

**Comment by lukaskubanek** [comment]
@toshi0383 @SuperWomble: Starting with [version 2.2.0](https://github.com/lukaskubanek/LoremSwiftum/releases/tag/v2.2.0), LoremSwiftum gained support for Swift Package Manager.

**Pull request closed without merging**
